version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.2
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      - image: redis:alpine
      - image: mongo:3.0

    working_directory: /go/src/github.com/kitakitabauer/circleci2.0

    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      AWS_DEFAULT_REGION: ap-northeast-1
      REGISTRY: 664653893268.dkr.ecr.ap-northeast-1.amazonaws.com

    steps:
      - checkout

      - run:
          name: Setup For Test
          command: |
            go version
            make setup

      - run:
          name: Run Tests
          command: |
            make cover

      - run:
          name: Install dependencies
          command: |
            curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
            sudo python get-pip.py
            sudo pip install awscli

      - setup_remote_docker:
          reusable: true

      - deploy:
          name: Deploy
          command: |
            echo "Deploy!!!!!!!"
            echo ${CIRCLE_BRANCH}
            echo ${CIRCLE_TAG}
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker -v
              eval $(aws ecr get-login --no-include-email --region ap-northeast-1)
              echo "ますたー!!!!!!"
              echo "これだけでいける"
            fi

            if [ "${CIRCLE_TAG}" =~ v.* ]; then
              echo "stagingやねん"
            fi

            if [ "${CIRCLE_TAG}" =~ release-v.* ]; then
              echo "productionやねん"
            fi

deployment:
  build:
    tag: /.*/
    command: |
      echo "これでフックされるらしい"
      echo ${CIRCLE_TAG}
