version: 2
jobs:
  build:
    docker:
      - image: golang:1.8.2-alpine
      - image: redis:alpine
      - image: mongo:3.0
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
    working_directory: /go/src/github.com/awa/${CIRCLE_PROJECT_REPONAME}
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      GOROOT: /usr/local/go
    steps:
      - checkout
#      - run:
#          name: Create Working Dir
#          command:
#            echo "Create Working Dir"

      - run:
          name: Setup For Test
          command: |
            go get github.com/mattn/goveralls |
            pwd |
            ls |
#      - run:
#          name: Run Tests
#          command: |
#            echo "Run Tests" |
#            make cover
#            bash <(curl -s https://codecov.io/bash) -t ed2dbec1-d62d-4a21-9ce7-5faf137350ac

      # - setup_remote_docker

      # This should go into custom primary image, here's only for the sake of explanation
#      - run:
#          name: Install Docker client
#          command: |
#            set -x
#            VER="17.03.0-ce"
#            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
#            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
#            mv /tmp/docker/* /usr/bin

#      - run:
#          name: Install Docker Compose
#          command: |
#            set -x
#            curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
#            chmod +x /usr/local/bin/docker-compose


