version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.2
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      - image: redis:alpine
      - image: mongo:3.0

    working_directory: /go/src/github.com/kitakitabauer/circleci2.0

    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      AWS_DEFAULT_REGION: ap-northeast-1
      REGISTRY: 664653893268.dkr.ecr.ap-northeast-1.amazonaws.com

    steps:
      - checkout

      - run:
          name: Setup For Test
          command: |
            go version
            make setup

      - run:
          name: Run Tests
          command: |
            make cover

      - deploy:
          name: Deploy Request
          command: |
            echo ${CIRCLE_BRANCH}
            echo ${CIRCLE_TAG}

            if [ "${CIRCLE_BRANCH}" == "master" ] || [[ "${CIRCLE_TAG}" =~ v.* ]]; then
              curl --user ${CIRCLE_API_TOKEN}: \
                --data build_parameters[CIRCLE_JOB]=deploy \
                --data revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/kitakitabauer/circleci2.0/tree/master \
                >> /dev/null
            fi

  deploy:
    docker:
      - image: circleci/golang:1.8.2
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"

    working_directory: /go/src/github.com/kitakitabauer/circleci2.0/deploy

    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      AWS_DEFAULT_REGION: ap-northeast-1
      REGISTRY: 664653893268.dkr.ecr.ap-northeast-1.amazonaws.com

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - run:
          name: Install dependencies
          command: |
            curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
            sudo python get-pip.py
            sudo pip install awscli

      - deploy:
          name: Deploy
          command: |
            echo "Deploy!!!!!!!"
            echo ${CIRCLE_BRANCH}
            echo ${CIRCLE_TAG}
            docker -v
            eval $(aws ecr get-login --no-include-email --region ap-northeast-1)

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "ますたー!!!!!!"
              echo "これだけでいける"
            fi

            if [[ "${CIRCLE_TAG}" =~ release-v.* ]]; then
              echo "productionやねん"
            elif [[ "${CIRCLE_TAG}" =~ v.* ]]; then
              echo "stagingやねん"
            fi

deployment_tag_hook:
  fake_deploy_for_cci2:
    tag: /.*/
    commands: echo "make tags run in 2.0"
